version: 3
services:
  smtp:
    build: .
    ports:
     - "25:25"
    environment:
      GMAIL_USER:
      GMAIL_PASSWORD:
      SES_USER:
      SES_PASSWORD:
      SES_REGION:
      RELAY_NETWORKS:
      RELAY_DOMAINS:
      KEY_PATH:
      CERTIFICATE_PATH:
      MAILNAME:
      SMARTHOST_ADDRESS: dailyinfo-co-uk.outbound1-uk.mailanyone.net
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s
